on: [push, pull_request]

jobs:
  linker:
    runs-on: ubuntu-latest
    name: Links branch issue pr
    steps:
      - name: Link
        id: Link
        uses: Gateway3B/BranchIssuePrLinker@main
        with:
          github-token: ${{ github.token }}
          pr-commit-message: ${{ github.event.commits[0].message }}
      - name: print
        run: echo "PR-Commit-Message - ${{ github.event.commits[0].message }}"